-- Run this complete file in Supabase SQL Editor before deploying.
-- Safe to run more than once. It creates/updates tables, policies and default content.

create table if not exists public.site_settings (
  id bigint primary key default 1,
  company_name text default 'Shree Radha Enterprises',
  tagline text default 'Comfort that moves with every step.',
  hero_subtitle text,
  hero_badge text default 'Premium comfort footwear',
  about_eyebrow text default 'About Us',
  about_title text default 'Designed for durability, support and daily comfort.',
  about_body text default 'We supply premium orthopedic slippers, comfort flip-flops and stylish ladies footwear for bulk buyers, dealers and retailers.',
  about_benefits text[] default array[
    'Orthopedic comfort focused designs',
    'Soft cushion and anti-slip options',
    'Bulk order, OEM and dealership support',
    'Stylish product range for men and women'
  ],
  feature1_title text default 'Manufacturing Support',
  feature1_text text default 'Bulk production for dealers and distributors.',
  feature2_title text default 'Quality Assurance',
  feature2_text text default 'Comfort, sole grip and finishing checked carefully.',
  feature3_title text default 'Bulk Supply',
  feature3_text text default 'Supply support for domestic and business orders.',
  catalog_eyebrow text default 'Product Catalog',
  catalog_title text default 'Premium footwear collection',
  catalog_subtitle text default 'Click any product to view full details and enquiry options.',
  contact_eyebrow text default 'Contact',
  contact_title text default 'Business Enquiry',
  contact_subtitle text default 'Send your bulk order, dealership or manufacturing requirement.',
  theme_color text default '#f59e0b',
  phone text,
  email text,
  address text,
  whatsapp text,
  instagram text,
  facebook text,
  youtube text,
  linkedin text,
  updated_at timestamptz default now()
);

-- Add missing columns when upgrading an older install.
alter table public.site_settings add column if not exists hero_badge text default 'Premium comfort footwear';
alter table public.site_settings add column if not exists about_eyebrow text default 'About Us';
alter table public.site_settings add column if not exists about_title text default 'Designed for durability, support and daily comfort.';
alter table public.site_settings add column if not exists about_body text default 'We supply premium orthopedic slippers, comfort flip-flops and stylish ladies footwear for bulk buyers, dealers and retailers.';
alter table public.site_settings add column if not exists about_benefits text[] default array['Orthopedic comfort focused designs','Soft cushion and anti-slip options','Bulk order, OEM and dealership support','Stylish product range for men and women'];
alter table public.site_settings add column if not exists feature1_title text default 'Manufacturing Support';
alter table public.site_settings add column if not exists feature1_text text default 'Bulk production for dealers and distributors.';
alter table public.site_settings add column if not exists feature2_title text default 'Quality Assurance';
alter table public.site_settings add column if not exists feature2_text text default 'Comfort, sole grip and finishing checked carefully.';
alter table public.site_settings add column if not exists feature3_title text default 'Bulk Supply';
alter table public.site_settings add column if not exists feature3_text text default 'Supply support for domestic and business orders.';
alter table public.site_settings add column if not exists catalog_eyebrow text default 'Product Catalog';
alter table public.site_settings add column if not exists catalog_title text default 'Premium footwear collection';
alter table public.site_settings add column if not exists catalog_subtitle text default 'Click any product to view full details and enquiry options.';
alter table public.site_settings add column if not exists contact_eyebrow text default 'Contact';
alter table public.site_settings add column if not exists contact_title text default 'Business Enquiry';
alter table public.site_settings add column if not exists contact_subtitle text default 'Send your bulk order, dealership or manufacturing requirement.';
alter table public.site_settings add column if not exists theme_color text default '#f59e0b';

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  category text,
  description text,
  detail text,
  image_url text,
  features text[] default '{}',
  mrp text default '',
  is_active boolean default true,
  sort_order int default 99,
  gallery_images jsonb default '[]',
  detail_sections jsonb default '[]',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.products add column if not exists gallery_images jsonb default '[]';
alter table public.products add column if not exists detail_sections jsonb default '[]';

create table if not exists public.home_stats (
  id bigint generated by default as identity primary key,
  value text not null,
  label text not null,
  sort_order int default 99,
  is_active boolean default true,
  updated_at timestamptz default now()
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  company text,
  email text not null,
  phone text not null,
  interest text,
  message text not null,
  status text default 'new',
  created_at timestamptz default now()
);

-- Remove duplicate default stats from previous schema runs, then prevent future duplicates.
delete from public.home_stats a
using public.home_stats b
where a.label = b.label and a.id > b.id;
create unique index if not exists home_stats_label_unique on public.home_stats(label);

alter table public.site_settings enable row level security;
alter table public.products enable row level security;
alter table public.home_stats enable row level security;
alter table public.inquiries enable row level security;

drop policy if exists "Public can read settings" on public.site_settings;
create policy "Public can read settings"
on public.site_settings for select
to anon, authenticated
using (true);

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
to anon, authenticated
using (is_active = true or auth.role() = 'authenticated');

drop policy if exists "Public can read active homepage stats" on public.home_stats;
create policy "Public can read active homepage stats"
on public.home_stats for select
to anon, authenticated
using (is_active = true or auth.role() = 'authenticated');

drop policy if exists "Public can submit inquiries" on public.inquiries;
create policy "Public can submit inquiries"
on public.inquiries for insert
to anon, authenticated
with check (true);

drop policy if exists "Admin can manage settings" on public.site_settings;
create policy "Admin can manage settings"
on public.site_settings for all
to authenticated
using (true)
with check (true);

drop policy if exists "Admin can manage products" on public.products;
create policy "Admin can manage products"
on public.products for all
to authenticated
using (true)
with check (true);

drop policy if exists "Admin can manage homepage stats" on public.home_stats;
create policy "Admin can manage homepage stats"
on public.home_stats for all
to authenticated
using (true)
with check (true);

drop policy if exists "Admin can manage inquiries" on public.inquiries;
create policy "Admin can manage inquiries"
on public.inquiries for all
to authenticated
using (true)
with check (true);

insert into public.site_settings (
  id, company_name, tagline, hero_subtitle, hero_badge, about_eyebrow, about_title, about_body, about_benefits,
  feature1_title, feature1_text, feature2_title, feature2_text, feature3_title, feature3_text,
  catalog_eyebrow, catalog_title, catalog_subtitle, contact_eyebrow, contact_title, contact_subtitle,
  theme_color, phone, email, address, whatsapp
)
values (
  1,
  'Shree Radha Enterprises',
  'Comfort that moves with every step.',
  'Shree Radha Enterprises manufactures orthopedic, lifestyle and fashion footwear with a premium comfort-first approach.',
  'Premium comfort footwear',
  'About Us',
  'Designed for durability, support and daily comfort.',
  'We supply premium orthopedic slippers, comfort flip-flops and stylish ladies footwear for bulk buyers, dealers and retailers.',
  array['Orthopedic comfort focused designs','Soft cushion and anti-slip options','Bulk order, OEM and dealership support','Stylish product range for men and women'],
  'Manufacturing Support', 'Bulk production for dealers and distributors.',
  'Quality Assurance', 'Comfort, sole grip and finishing checked carefully.',
  'Bulk Supply', 'Supply support for domestic and business orders.',
  'Product Catalog', 'Premium footwear collection', 'Click any product to view full details and enquiry options.',
  'Contact', 'Business Enquiry', 'Send your bulk order, dealership or manufacturing requirement.',
  '#f59e0b',
  '+91 7679217474',
  'thefamouschappal@gmail.com',
  'Nangloi, New Delhi',
  '917679217474'
)
on conflict (id) do update set
  company_name = coalesce(public.site_settings.company_name, excluded.company_name),
  tagline = coalesce(public.site_settings.tagline, excluded.tagline),
  hero_subtitle = coalesce(public.site_settings.hero_subtitle, excluded.hero_subtitle),
  hero_badge = coalesce(public.site_settings.hero_badge, excluded.hero_badge),
  about_eyebrow = coalesce(public.site_settings.about_eyebrow, excluded.about_eyebrow),
  about_title = coalesce(public.site_settings.about_title, excluded.about_title),
  about_body = coalesce(public.site_settings.about_body, excluded.about_body),
  about_benefits = coalesce(public.site_settings.about_benefits, excluded.about_benefits),
  feature1_title = coalesce(public.site_settings.feature1_title, excluded.feature1_title),
  feature1_text = coalesce(public.site_settings.feature1_text, excluded.feature1_text),
  feature2_title = coalesce(public.site_settings.feature2_title, excluded.feature2_title),
  feature2_text = coalesce(public.site_settings.feature2_text, excluded.feature2_text),
  feature3_title = coalesce(public.site_settings.feature3_title, excluded.feature3_title),
  feature3_text = coalesce(public.site_settings.feature3_text, excluded.feature3_text),
  catalog_eyebrow = coalesce(public.site_settings.catalog_eyebrow, excluded.catalog_eyebrow),
  catalog_title = coalesce(public.site_settings.catalog_title, excluded.catalog_title),
  catalog_subtitle = coalesce(public.site_settings.catalog_subtitle, excluded.catalog_subtitle),
  contact_eyebrow = coalesce(public.site_settings.contact_eyebrow, excluded.contact_eyebrow),
  contact_title = coalesce(public.site_settings.contact_title, excluded.contact_title),
  contact_subtitle = coalesce(public.site_settings.contact_subtitle, excluded.contact_subtitle),
  theme_color = coalesce(public.site_settings.theme_color, excluded.theme_color);

insert into public.home_stats (value, label, sort_order, is_active)
values
('5000+', 'Daily Pair Capacity', 1, true),
('15+', 'Years Experience', 2, true),
('200+', 'Dealer Network', 3, true),
('100%', 'Quality Checked', 4, true)
on conflict (label) do update set
  value = excluded.value,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

-- Product image upload storage for admin dashboard.
-- The bucket is public so uploaded product images can display on the website.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 2097152, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
  public = true,
  file_size_limit = 2097152,
  allowed_mime_types = array['image/jpeg','image/png','image/webp'];

drop policy if exists "Public can read product images" on storage.objects;
create policy "Public can read product images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'product-images');

drop policy if exists "Admin can upload product images" on storage.objects;
create policy "Admin can upload product images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-images');

drop policy if exists "Admin can update product images" on storage.objects;
create policy "Admin can update product images"
on storage.objects for update
to authenticated
using (bucket_id = 'product-images')
with check (bucket_id = 'product-images');

drop policy if exists "Admin can delete product images" on storage.objects;
create policy "Admin can delete product images"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-images');
